-- Plugin Configuration
-- Add your custom plugins or override LazyVim plugins here
--
-- Plugin Categories:
-- - ui.lua: UI-related plugins (colorschemes, statusline, etc.)
-- - editor.lua: Editor enhancements (telescope, treesitter, etc.)
-- - lsp.lua: LSP and language support
-- - disabled.lua: Plugins to disable from LazyVim
--
-- How to disable LazyVim plugins:
-- 1. Find the plugin in: ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/
-- 2. Add it to disabled.lua like:
--    { "lukas-reineke/indent-blankline.nvim", enabled = false },
--
-- Common plugins to disable:
-- - indent-blankline.nvim: Shows vertical indent lines
-- - mini.indentscope: Shows indentation scope
-- - nvim-cmp: Autocompletion (use nvim-cmp replacement if needed)
-- - alpha-nvim: Dashboard
-- - neo-tree.nvim: File explorer
-- - telescope.nvim: Fuzzy finder
-- - trouble.nvim: Diagnostics list
-- - which-key.nvim: Keymap popup
--
-- To find plugin names, run: :Lazy health
